<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>Tool Preset Holder</text>

        <Action name="tph_select_brush">
            <icon></icon>
            <text>tph select tool brush</text>
            <whatsThis></whatsThis>
            <toolTip></toolTip>
            <iconText></iconText>
            <activationFlags>0</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut>b</shortcut>
            <isCheckable>false</isCheckable>
            <statusTip></statusTip>
        </Action>
        <Action name="tph_select_eraser">
            <icon></icon>
            <text>tph select tool eraser</text>
            <whatsThis></whatsThis>
            <toolTip></toolTip>
            <iconText></iconText>
            <activationFlags>0</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut>e</shortcut>
            <isCheckable>false</isCheckable>
            <statusTip></statusTip>
        </Action>
        <Action name="tph_select_blender">
            <icon></icon>
            <text>tph select tool smudge</text>
            <whatsThis></whatsThis>
            <toolTip></toolTip>
            <iconText></iconText>
            <activationFlags>0</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut>r</shortcut>
            <isCheckable>false</isCheckable>
            <statusTip></statusTip>
        </Action>
	<Action name="tph_select_adjust_light">
            <icon></icon>
            <text>tph select tool adjust light</text>
            <whatsThis></whatsThis>
            <toolTip></toolTip>
            <iconText></iconText>
            <activationFlags>0</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut></shortcut>
            <isCheckable>false</isCheckable>
            <statusTip></statusTip>
        </Action>
	<Action name="tph_select_clone">
            <icon></icon>
            <text>tph select tool clone</text>
            <whatsThis></whatsThis>
            <toolTip></toolTip>
            <iconText></iconText>
            <activationFlags>0</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut></shortcut>
            <isCheckable>false</isCheckable>
            <statusTip></statusTip>
	<Action name="tph_select_distort">
            <icon></icon>
            <text>tph select tool distort</text>
            <whatsThis></whatsThis>
            <toolTip></toolTip>
            <iconText></iconText>
            <activationFlags>0</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut></shortcut>
            <isCheckable>false</isCheckable>
            <statusTip></statusTip>
        </Action>
    </Actions>
</ActionCollection>